version: '3.8'
services:
    frontend:
        env_file: .env
        networks:
            - back_net
            - bridge_net
        extends:
            file: ./frontend/docker-compose.yml
            service: app
        depends_on:
            - backend
            - storage
            - cache
    backend:
        env_file: .env
        networks:
            - back_net
            - bridge_net
        extends:
            file: ./backend/docker-compose.yml
            service: app
        depends_on:
            - storage
            - cache
#    game_machine:
#        networks:
#            - back_net
#            - bridge_net
#        extends:
#            file: ./game_machine/docker-compose.yml
#            service: app
    cache:
        env_file: .env
        extends:
            file: ./backend/docker-compose.yml
            service: cache
        networks:
            - back_net
    storage:
        env_file: .env
        networks:
            - back_net
        extends:
            file: ./storage/docker-compose.yml
            service: database
        volumes:
            - ./db/postgresql:/var/lib/postgresql

networks:
    back_net:
        external: false
    bridge_net:
        driver: bridge