version: '3.8'
services:
    frontend:
        env_file: .env
        networks:
            - back_net
            - bridge_net
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        extends:
            file: ./frontend/docker-compose.yml
            service: app
    backend:
        env_file: .env
        networks:
            - back_net
            - bridge_net
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        extends:
            file: ./backend/docker-compose.yml
            service: app
        depends_on:
            - storage
            - cache
    game_machine:
        env_file: .env
        networks:
            - back_net
        ports:
            - ${GAME_MACHINE_PORT}:${GAME_MACHINE_PORT}
        extends:
            file: ./game_machine/docker-compose.yml
            service: app
        depends_on:
            - storage
            - cache
    cache:
        env_file: .env
        extends:
            file: ./backend/docker-compose.yml
            service: cache
        networks:
            - back_net
    storage:
        env_file: .env
        volumes:
            - ./storage/db/postgresql:/var/lib/postgresql
        networks:
            - back_net
            - bridge_net
        extends:
            file: ./storage/docker-compose.yml
            service: database
#    loki:
#        env_file: .env
#        networks:
#            - back_net
#        extends:
#            file: ./audit/docker-compose.yml
#            service: loki
#    grafana:
#        env_file: .env
#        networks:
#            - back_net
#            - bridge_net
#        extends:
#            file: ./audit/docker-compose.yml
#            service: grafana
#    keycloak:
#        networks:
#            - back_net
#            - bridge_net
#        extends:
#            file: ./storage/docker-compose.yml
#            service: keycloak
networks:
    back_net:
        external: false
    bridge_net:
        driver: bridge