version: '3.8'
services:
#    frontend:
#        extends:
#            file: ./frontend/docker-compose.yml
#            service: app
#    backend:
#        extends:
#            file: ./backend/docker-compose.yml
#            service: app
#    game_machine:
#        extends:
#            file: ./game_machine/docker-compose.yml
#            service: app
    cache:
        extends:
            file: ./backend/docker-compose.yml
            service: memcached
        networks:
            - back_net
        environment:
            - MEMCACHED_USERNAME=root
            - MEMCACHED_PASSWORD=123456
    storage:
        networks:
            - back_net
        extends:
            file: ./storage/docker-compose.yml
            service: database
#        environment:
#            - POSTGRES_USER=root
#            - POSTGRES_PASSWORD=123456
#            - POSTGRES_DB=warlords

networks:
    back_net:
        external: false
    bridge_net:
        driver: bridge